### PR TITLE
chore: improve perf of hot path

### PR DESCRIPTION
**Pull request by Uzlopak**
Reduce the hot path in core ;)

An investigation regarding the hotpaths showed that the console.warn and .error binding results take some time. Also a forEach call is Kind of hot.

To improve the performance console.warn and console.error are bound once at startup. 
before
Screenshot from 2023-11-20 23-11-43

Resolves #ISSUE_NUMBER

---

### Before the change?

-

### After the change?

-

### Pull request checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

---

### CODE REVIEW

**Comment by Uzlopak** [comment]
@wolfy1339 
@gr2m

**Comment by wolfy1339** [comment]
Can you describe the fix and the problem with text instead of just a picture next time.

It would help with searchability and context in the future if this comes back up

**Comment by Uzlopak** [comment]
@wolfy1339 added some context

**Review by gr2m — COMMENTED** [review]
a `chore:` commit will not trigger a new release. Improving performance without changing behavior is a `fix:`

**Pull request merged**
