### PR TITLE
ci: add NodeJS v16 to test matrix

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Comment by wolfy1339** [comment]
The tests for NodeJS v16 fail with this message:
```
FAIL test/hook.test.ts
  ● Test suite failed to run

    test/hook.test.ts:136:35 - error TS2345: Argument of type '(error: any, requestOptions: any) => { data: { ok: boolean; }; }' is not assignable to parameter of type 'ErrorHook<Required<EndpointDefaults>, RequestError | Error>'.
      Type '{ data: { ok: boolean; }; }' is not assignable to type 'void | Promise<void>'.
        Type '{ data: { ok: boolean; }; }' is missing the following properties from type 'Promise<void>': then, catch, [Symbol.toStringTag], finally

    136     octokit.hook.error("request", (error: any, requestOptions: any) => {
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I don't understand why it would fail on NodeJS v16 and not others

**Comment by gr2m** [comment]
Did you write a script to create all these PRs?

**Comment by wolfy1339** [comment]
I did them all by hand. No script

**Comment by gr2m** [comment]
> I did them all by hand. No script

would be a great candidate for an @octoherd script :) Let me know next time you have a situation like this, happy to pair on it

**Comment by gr2m** [comment]
the error makes no sense to me either. Feel free to add a 

```ts
// @ts-ignore - Workaround for Node 16 (https://github.com/octokit/core.js/pull/329)
```

**Comment by gr2m** [comment]
hey how about we pair on creating a script to merge all these PRs? That's what I'd do anyway, it might take roughly the same time as reviewing them all by hand, but in the end we have a script that can merge PRs automatically that match certain criteria

**Comment by gr2m** [comment]
I did the live coding session I mentioned on twitch. It was the first time I tried it and my audio was all whack in the beginning, and I lost connectivity twice 🤷🏼 

https://www.twitch.tv/gregorcodes

But here is the resulting script: https://github.com/gr2m/octoherd-script-merge-pull-requests/

**Pull request merged**
