### PR TITLE
build(deps): replace `@gr2m/fetch-mock` with `fetch-mock`

### PR DESCRIPTION
**Pull request by wolfy1339**
----

### Before the change?

* Used a custom fork of `fetch-mock` for Fetch API support

### After the change?

* Use the `fetch-mock` module again, it has been updated to support the Fetch API

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by wolfy1339** [comment]
The tests are failing because of some type errors with `fetch-mock`, otherwise the tests are passing

**Comment by oscard0m** [comment]
> The tests are failing because of some type errors with `fetch-mock`, otherwise the tests are passing

Are these type errors something we can fix on our end or it needs work in `fetch-mock`?

**Comment by wolfy1339** [comment]
> Are these type errors something we can fix on our end or it needs work in `fetch-mock`?

These type errors are not because of our code. We could always override the types, but that's not a great way to do it over the 50 repositories that use `fetch-mock`.

See this PR https://github.com/wheresrhys/fetch-mock/pull/680

It's because the package offers CJS+ESM but the types only have a CJS export and this TypeScript complains that there is no `default` export defined.

The problem has been fixed, just waiting for the release to drop on npm

**Comment by wolfy1339** [comment]
This is now ready to merge

**Review by gr2m — APPROVED** [review]

**Pull request merged**
